name: Build and Test

on:
  pull_request:
    branches: ["master"]

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: build and test
        working-directory: ./my-app
        run: |
          npm install
          CI=false npm run build
